---
title: "COVID case data"
author: "Sid Gupta"
date: '2022-01-12'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# Import the required libraries for this project.
#install.packages("opendatatoronto")
#install.packages("ggmap")
library(ggmap)
library(dplyr)
library(forcats)
library(knitr)
library(janitor)
library(lubridate)
library(opendatatoronto)
library(tidyverse)
library(tidyr)

```


```{r}
# Read in the COVID19 cases dataset from opendatatoronto.
covid_cases <- read_csv("../inputs/data/COVID19_cases.csv")
```

```{r}
# Clean the dataset and split it into Outbreak and Sporadic groups
covid_cases_clean <-
  covid_cases |> 
  clean_names()

covid_cases_outbreak <-
  covid_cases_clean |> 
  filter(outbreak_associated == "Outbreak Associated")

covid_cases_sporadic <-
  covid_cases_clean |> 
  filter(outbreak_associated == "Sporadic")
```

```{r}
# Get a count of the sources in both groups. Add a new column that explains what each source means.
outbreak_settings <-
  covid_cases_outbreak |>
  count(source_of_infection) |>
  mutate(n = n / sum(n)) |>
  arrange(desc(n))
print(outbreak_settings)
```
```{r}
sporadic_settings <-
  covid_cases_sporadic |>
  count(source_of_infection) |> 
  mutate(n = n / sum(n)) |>
  arrange(desc(n))
print(sporadic_settings)
```
```{r}
# Get the demographics of the "No information" cases labelled as Sporadic.
sporadic_no_info <-
  covid_cases_sporadic |>
  filter(source_of_infection == "No Information")

print(sporadic_no_info)
```

```{r}

show_col_count <- function(table, col) {
  table_col_count <-
    table |>
    count({{col}}) |>
    mutate(n = n / sum(n)) |>
    arrange(desc(n))
  return(table_col_count)
}

sporadic_no_info_age_count <- show_col_count(sporadic_no_info, age_group)
sporadic_no_info_age_count <- show_col_count(sporadic_no_info, neighbourhood_name)
sporadic_no_info_age_count <- show_col_count(sporadic_no_info, episode_date)
sporadic_no_info_age_count <- show_col_count(sporadic_no_info, episode_date)
print(sporadic_no_info_age_count)
```

```{r}

for (var in names(sporadic_no_info)) {
  asdf <- 
    sporadic_no_info |>
    count(.data[[var]]) |>
    mutate(n = n / sum(n)) |>
    arrange(desc(n))
  print(asdf)
}

#lapply(names(sporadic_no_info), function(var) sporadic_no_info %>% count(.data[[var]]))

```


```{r}
for (var in names(covid_cases_outbreak)) {
  asdf <- 
    covid_cases_outbreak |>
    count(.data[[var]]) |>
    mutate(n = n / sum(n)) |>
    arrange(desc(n))
  print(asdf)
}

```

```{r}
sporadic_info <-
  covid_cases_sporadic |>
  filter(source_of_infection != "No Information")

for (var in names(sporadic_info)) {
  asdf <- 
    sporadic_info |>
    count(.data[[var]]) |>
    mutate(n = n / sum(n)) |>
    arrange(desc(n))
  print(asdf)
}
```

```{r}
for (var in names(covid_cases_clean)) {
  asdf <- 
    covid_cases_clean |>
    count(.data[[var]]) |>
    mutate(n = n / sum(n)) |>
    arrange(desc(n))
  print(asdf)
}
```


```{r}

```


```{r}
```


```{r}
```


```{r}
```


```{r}
```



